version: '1.0.0'

# Uncomment environment, if you want to use debug mode.

services:
  web:
    build: .
    ports:
      - '3000:3000'
    volumes:
      - '.:/usr/src/app'
    command: air cmd/main.go
    #environment:
      #- DEBUG=true
  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - '5432:5432'
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:
